---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-account-creds
  namespace: ${CROSSPLANE_NS}
type: Opaque
data:
  credentials: ${BASE64ENCODED_GCP_PROVIDER_CREDS}
---
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: ${GCP_PROJECT_ID}
  credentials:
    source: Secret
    secretRef:
      namespace: ${CROSSPLANE_NS}
      name: gcp-account-creds
      key: credentials